daftar_event/urls.py
from django.urls import path
from daftar_event.views import daftar_event1, daftar_event2, kategori

app_name = 'daftar_event'

urlpatterns = [
    path('daftar_event1/', daftar_event1, name='daftar_event1'),
    path('daftar_event2/', daftar_event2, name='daftar_event2'),
    path('kategori/', kategori, name='kategori'),
]

tk_babadu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('authentication.urls', 'authentication'),)),
    path('ujian-kualifikasi/', include(('ujian_kualifikasi.urls', 'ujian_kualifikasi'),)),
    path('daftar-atlet/', include(('daftar_atlet.urls', 'daftar_atlet'),)),
    path('pertandingan2/', include(('pertandingan2.urls', 'pertandingan2'),)),
    path('daftar-event/', include(('daftar_event.urls', 'daftar_event'),)),
    path('dashboard-event/', include(('dashboard_event.urls', 'dashboard_event'),)),
]

daftar_event/models.py
from django.db import models

# Create your models here.

daftar_event/views.py
from django.shortcuts import render
from utils.query import *
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest
import random
from django.shortcuts import render, redirect
from django.db import connection


def daftar_event1(request):
    # role = request.COOKIES.get('role')

    with connection.cursor() as cursor:
        cursor.execute("SELECT nama, negara, kapasitas FROM stadium")
        stadiums = cursor.fetchall()

    print(stadiums)

    context = {
        'stadiums': stadiums
    }

    return render(request, "daftar_event1.html", context)

def dict_fetch_all(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def daftar_event2(request):
    stadium_name = request.POST.get('stadium_name', '')

    with connection.cursor() as cursor:
        cursor.execute("SELECT nama_event, total_hadiah, tgl_mulai, kategori_superseries "
                       "FROM event WHERE nama_stadium = %s AND tgl_mulai > current_date", [stadium_name])
        events = dict_fetch_all(cursor)  # Fetch all rows as dictionaries

    context = {
        'stadium_name': stadium_name,
        'events': events
    }

    return render(request, "daftar_event2.html", context)

def dict_fetch_one(cursor):
    columns = [col[0] for col in cursor.description]
    return dict(zip(columns, cursor.fetchone()))

def kategori(request):
    if request.method == 'POST':
        nama_event = request.POST.get('nama_event')

        # Get event details
        with connection.cursor() as cursor:
            cursor.execute("SELECT nama_event, total_hadiah, tgl_mulai, tgl_selesai, kategori_superseries, stadium.nama, stadium.kapasitas, event.negara "
                           "FROM event "
                           "INNER JOIN stadium ON event.nama_stadium = stadium.nama "
                           "WHERE event.nama_event = %s", [nama_event])
            event_details = cursor.fetchone()

        # Get matches for the selected event
        with connection.cursor() as cursor:
            cursor.execute("SELECT pk.jenis_partai, pk.nama_event, pk.tahun_event, "
                   "ppk.nomor_peserta, pg.id_atlet_ganda "
                   "FROM partai_kompetisi pk "
                   "LEFT JOIN partai_peserta_kompetisi ppk ON pk.jenis_partai = ppk.jenis_partai "
                   "AND pk.nama_event = ppk.nama_event "
                   "AND pk.tahun_event = ppk.tahun_event "
                   "LEFT JOIN peserta_kompetisi p ON ppk.nomor_peserta = p.nomor_peserta "
                   "LEFT JOIN atlet_ganda pg ON p.id_atlet_ganda = pg.id_atlet_ganda "
                   "WHERE pk.nama_event = %s", [nama_event])
            matches = cursor.fetchall()

        context = {
            'nama_event': nama_event,
            'event_details': event_details,
            'matches': matches
        }
        return render(request, 'kategori.html', context)
    else:
        return HttpResponseBadRequest("Invalid request method")

daftar_event/templates/daftar_event1.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer"
    />
    {% comment %} <link rel="stylesheet" href="{% static 'css/base.css' %}" /> {% endcomment %}
    <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


</head>

<style>
    body {
        background: url('https://source.unsplash.com/twukN12EN7c/1920x1080') no-repeat center center fixed;
    }
    
    th {
        text-align: center;
    }
</style>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <!-- Container wrapper -->
        <div class="container-fluid">
            <!-- Toggle button -->
            <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>

            <!-- Collapsible wrapper -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Navbar brand -->
                <a class="navbar-brand mt-2 mt-lg-0" href="#">
                    <img src="https://comunidadbabadu.com/wp-content/uploads/2023/01/Babadu-Logo.png" height="30" alt="MDB Logo" loading="lazy" />
                    <span class="badge rounded-pill badge-notification bg-success">Atlet</span>

                </a>

                <!-- Left links -->
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Dashboard</a>


                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ujian_kualifikasi:show_riwayat' %}">Tes Kualifikasi</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'daftar_event:daftar_event1' %}"><b>Daftar Event</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Enrolled Event</a>
                    </li>
                </ul>
                <!-- Left links -->
            </div>
            <!-- Collapsible wrapper -->

            <!-- Right elements -->
            <div class="d-flex align-items-center">
                <!-- Icon -->
                <button type="button" class="btn btn-danger mx-2 ">Log Out</button>
            </div>
            <!-- Right elements -->
        </div>
        <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
    <br>
    <br>
    <h2 class="text-center"><b>DAFTAR EVENT</b></h2>
    <p class="text-center">Fitur ini digunakan bagi para atlet untuk mendaftarkan dirinya pada event yang akan berlangsung.</p>
    <br>
    <br>
    <div class="row justify-content-center">
        <table style="width: auto;" class="table table-bordered table-light table-striped table-hover">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">Nama Stadium</th>
                    <th scope="col">Negara</th>
                    <th scope="col">Kapasitas</th>
                    <th scope="col">Info</th>
                </tr>
            </thead>
            <tbody>
                {% for stadium in stadiums %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{stadium.0}}</td>
                    <td>{{stadium.1}}</td>
                    <td>{{stadium.2}}</td>
                    {% comment %} <td>
                        <a href="{% url 'daftar_event:daftar_event2' %}">
                        <button type="button" class="btn btn-info mx-2 ">Pilih</button>
                        </a>
                    </td> {% endcomment %}
                    <td>
                        <form action="{% url 'daftar_event:daftar_event2' %}" method="post">
                          {% csrf_token %}
                          <input type="hidden" name="stadium_name" value="{{ stadium.0 }}">
                          <button type="submit">Pilih</button>
                        </form>
                      </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>


</body>

</html>

daftar_event/templates/daftar_event2.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer"
    />
    {% comment %} <link rel="stylesheet" href="{% static 'css/base.css' %}" /> {% endcomment %}
    <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


</head>

<style>
    body {
        background: url('https://source.unsplash.com/twukN12EN7c/1920x1080') no-repeat center center fixed;
    }
    
    th {
        text-align: center;
    }
</style>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <!-- Container wrapper -->
        <div class="container-fluid">
            <!-- Toggle button -->
            <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>

            <!-- Collapsible wrapper -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Navbar brand -->
                <a class="navbar-brand mt-2 mt-lg-0" href="#">
                    <img src="https://comunidadbabadu.com/wp-content/uploads/2023/01/Babadu-Logo.png" height="30" alt="MDB Logo" loading="lazy" />
                    <span class="badge rounded-pill badge-notification bg-success">Atlet</span>

                </a>

                <!-- Left links -->
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Dashboard</a>


                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ujian_kualifikasi:show_riwayat' %}">Tes Kualifikasi</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'daftar_event:daftar_event1' %}"><b>Daftar Event</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Enrolled Event</a>
                    </li>
                </ul>
                <!-- Left links -->
            </div>
            <!-- Collapsible wrapper -->

            <!-- Right elements -->
            <div class="d-flex align-items-center">
                <!-- Icon -->
                <button type="button" class="btn btn-danger mx-2 ">Log Out</button>
            </div>
            <!-- Right elements -->
        </div>
        <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
    <br>
    <br>
    <h2 class="text-center"><b>DAFTAR EVENT</b></h2>
    <p class="text-center">Fitur ini digunakan bagi para atlet untuk mendaftarkan dirinya pada event yang akan berlangsung.</p>
    <br>
    <br>
    <div class="row justify-content-center">
        <table style="width: auto;" class="table table-bordered table-info table-striped table-hover">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">Nama Event</th>
                    <th scope="col">Total Hadiah</th>
                    <th scope="col">Tanggal Mulai</th>
                    <th scope="col">Kategori</th>
                    <th scope="col">Daftar</th>
                </tr>
            </thead>
            <tbody>
                {% for event in events %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ event.nama_event }}</td>
                    <td>{{ event.total_hadiah }}</td>
                    <td>{{ event.tgl_mulai }}</td>
                    <td>{{ event.kategori_superseries }}</td>
                    <td>
                    <form action="{% url 'daftar_event:kategori' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="nama_event" value="{{ event.nama_event }}">
                        <button type="submit" class="btn-sm rounded-pill btn-warning">Pilih Event</button>
                    </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>


</body>

</html>

daftar_event/templates/kategori.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer"
    />
    {% comment %} <link rel="stylesheet" href="{% static 'css/base.css' %}" /> {% endcomment %}
    <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


</head>

<style>
    body {
        background: url('https://source.unsplash.com/twukN12EN7c/1920x1080') no-repeat center center fixed;
    }
    
    th {
        text-align: center;
    }
    
    td {
        text-align: center;
    }
    
    .card {
        margin: 0 auto;
        /* Added */
        float: none;
        /* Added */
        margin-bottom: 10px;
        /* Added */
    }
</style>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <!-- Container wrapper -->
        <div class="container-fluid">
            <!-- Toggle button -->
            <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>

            <!-- Collapsible wrapper -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Navbar brand -->
                <a class="navbar-brand mt-2 mt-lg-0" href="#">
                    <img src="https://comunidadbabadu.com/wp-content/uploads/2023/01/Babadu-Logo.png" height="30" alt="MDB Logo" loading="lazy" />
                    <span class="badge rounded-pill badge-notification bg-success">Atlet</span>

                </a>

                <!-- Left links -->
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Dashboard</a>


                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ujian_kualifikasi:ujian' %}">Tes Kualifikasi</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'daftar_event:daftar_event1' %}"><b>Daftar Event</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Enrolled Event</a>
                    </li>
                </ul>
                <!-- Left links -->
            </div>
            <!-- Collapsible wrapper -->

            <!-- Right elements -->
            <div class="d-flex align-items-center">
                <!-- Icon -->
                <button type="button" class="btn btn-danger mx-2 ">Log Out</button>
            </div>
            <!-- Right elements -->
        </div>
        <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
    <br>
    <br>
    <h2 class="text-center"><b>FORM PEMILIHAN PARTAI KOMPETISI</b></h2>
    <br>
    <br>
    <div style="width: 500px; height: 260px;" class="card bg-light row justify-content-center">
        <h6 class="text-center">Event: {{ event_details.0 }}</h6>
        <h6 class="text-center">Hadiah: {{ event_details.1 }}</h6>
        <h6 class="text-center">Tanggal Mulai: {{ event_details.2 }}</h6>
        <h6 class="text-center">Tanggal Selesai: {{ event_details.3 }}</h6>
        <h6 class="text-center">Kategori: {{ event_details.4 }}</h6>
        <h6 class="text-center">Kapasitas: {{event_details.6}}</h6>
        <h6 class="text-center">Stadium: {{ event_details.5 }}</h6>
        <h6 class="text-center">Negara: {{ event_details.7 }}</h6>
    </div>
    <br>
    <br>
    <div class="row justify-content-center">
        <table style="width: 520px;" class="table table-bordered table-light table-striped table-hover">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">Kategori</th>
                    <th scope="col">Partner</th>
                    <th scope="col">Kapasitas</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for match in matches %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ match.0 }}</td>
                    <td>
                        {% if match.0 == 'MD' or match.0 == 'WD' or match.0 == 'XD' %}
                        <select>
                        <option value="">Select Partner</option>
                        <option value="{{ match.0 }}">{{ match.0 }}</option>
                        </select>
                        {% else %}
                        -
                        {% endif %}
                    </td>
                    <td>{{ match.5 }} / {{ event_details.6 }}</td>
                    <td>
                        {% if event_details.6 > 0 %}
                        <button type="button" class="btn rounded-pill btn-success mx-2">Join</button>
                        {% else %}
                        <button type="button" class="btn rounded-pill btn-secondary mx-2" disabled>Full</button>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>


</body>

</html>