daftar_atlet/urls.py
from django.urls import path
from daftar_atlet.views import show_daftar_atlet

app_name = 'daftar_atlet'

urlpatterns = [
    path('', show_daftar_atlet, name='show_daftar_atlet'),
]

daftar_event/urls.py
from django.urls import path
from daftar_event.views import daftar_event1, daftar_event2, kategori

app_name = 'daftar_event'

urlpatterns = [
    path('daftar_event1/', daftar_event1, name='daftar_event1'),
    path('daftar_event2/', daftar_event2, name='daftar_event2'),
    path('kategori/', kategori, name='kategori'),
]

dashboard_event/urls.py
from django.urls import path
from dashboard_event.views import *

app_name = 'dashboard_event'

urlpatterns = [
    path('enrolled_event', enrolled_event_table, name='enrolled_event_table'),
    path('', enrolled_partai, name='enrolled_partai'),
    path('create_sponsor', create_sponsor, name='create_sponsor'),
    path('read_sponsor', read_sponsor, name='read_sponsor'),
    path('sponsor_card', sponsor_card, name='sponsor_card'),
    path('logout/', logout, name='logout'),
]

pertandingan2/urls.py
from django.urls import path
from pertandingan2.views import *

app_name = "pertandingan2"

urlpatterns = [
    path("", list_pertandingan, name="list_pertandingan"),
    path("create_pertandingan/", create_pertandingan, name="create_pertandingan"),
    path(
        "create_pertandingan_R32/create_pertandingan_R16/create_pertandingan_PerempatFinal/create_pertandingan_SemiFinal/create_pertandingan_Final/",
        create_pertandingan_Final,
        name="create_pertandingan_Final",
    ),
    path(
        "create_pertandingan_R32/create_pertandingan_R16/create_pertandingan_PerempatFinal/create_pertandingan_SemiFinal/",
        create_pertandingan_SemiFinal,
        name="create_pertandingan_SemiFinal",
    ),
    path(
        "create_pertandingan_R32/create_pertandingan_R16/create_pertandingan_PerempatFinal/",
        create_pertandingan_PerempatFinal,
        name="create_pertandingan_PerempatFinal",
    ),
    path(
        "create_pertandingan_R32/create_pertandingan_R16/",
        create_pertandingan_R16,
        name="create_pertandingan_R16",
    ),
    path(
        "create_pertandingan_R32/",
        create_pertandingan_R32,
        name="create_pertandingan_R32",
    ),
]

tk_babadu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('authentication.urls', 'authentication'),)),
    path('ujian-kualifikasi/', include(('ujian_kualifikasi.urls', 'ujian_kualifikasi'),)),
    path('daftar-atlet/', include(('daftar_atlet.urls', 'daftar_atlet'),)),
    path('pertandingan2/', include(('pertandingan2.urls', 'pertandingan2'),)),
    path('daftar-event/', include(('daftar_event.urls', 'daftar_event'),)),
    path('dashboard-event/', include(('dashboard_event.urls', 'dashboard_event'),)),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
      crossorigin="anonymous"
  />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
      integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <script
      src="https://code.jquery.com/jquery-3.6.1.js"
      integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI="
      crossorigin="anonymous"
    ></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    {% block meta %}
     {% endblock meta %}
  </head>

  <body>
    {% include 'navbar-all.html' %}

    {% block content %}
    <!-- include navbar -->
     {% endblock content %}
  </body>
  <!-- block for java script -->
  {% block script %} {% endblock script %}
</html>

templates/navbar copy.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
      crossorigin="anonymous"
  />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
      integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <script
      src="https://code.jquery.com/jquery-3.6.1.js"
      integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI="
      crossorigin="anonymous"
    ></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


  </head>

  <body>
    <!-- Navbar -->
<nav class="shadow navbar navbar-expand-lg navbar-light bg-light">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navbar brand -->
      <a class="navbar-brand mt-2 mt-lg-0" href="#">
        <img
          src="https://comunidadbabadu.com/wp-content/uploads/2023/01/Babadu-Logo.png"
          height="30"
          alt="MDB Logo"
          loading="lazy"
        />

      </a>
      
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       
       
      </ul>
      <!-- Left links -->

    </div>
    <!-- Collapsible wrapper -->

    <!-- Right elements -->
    <div class="d-flex align-items-center">
      <form class="form-inline my-2 my-lg-0">
        <!-- show this item when user is logged in  -->
        {% if role is not none  %}
        <a class="btn btn-outline-danger my-2 my-sm-0" type="submit" href="{% url 'authentication:logout' %}">Logout</a>
        {% endif %}
      </form>
      <!-- Icon -->
    </div>
    <!-- Right elements -->
   
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->


  </body>
</html>

templates/navbar-all.html
{% load static %}
{% block meta %}
{% endblock meta %}
{% block content %}

{% if role == "atlet-kualifikasi" %}
        <!-- Navbar untuk Atlet -->
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <a class="navbar-brand mt-2 mt-lg-0" href="#">
        <img src="https://comunidadbabadu.com/wp-content/uploads/2023/01/Babadu-Logo.png" height="30" alt="MDB Logo" loading="lazy" />
        <span class="badge rounded-pill badge-notification bg-success">Atlet Kualifikasi</span>
      </a>

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authentication:home' %}">Dashboard</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Ujian Kualifikasi
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% comment %} Atur href dibagian ini yah {% endcomment %}
            <a class="dropdown-item" href="{% url 'ujian_kualifikasi:show_ujian' %}">List Ujian Kualifikasi</a>
            <a class="dropdown-item" href="{% url 'ujian_kualifikasi:show_riwayat' %}">Riwayat Ujian Kualifikasi</a>
          </div>
        </li>

                <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Event
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% comment %} Atur href dibagian ini yah {% endcomment %}
            <a class="dropdown-item" href="{% url 'daftar_event:daftar_event1' %}">Daftar Event</a>
            <a class="dropdown-item" href="{% url 'dashboard_event:enrolled_event_table' %}">Enrolled Event</a>
          </div>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Sponsor
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% comment %} Atur href dibagian ini yah {% endcomment %}
            <a class="dropdown-item" href="{% url 'dashboard_event:create_sponsor' %}">Daftar Sponsor</a>
            <a class="dropdown-item" href="{% url 'dashboard_event:read_sponsor' %}">List Sponsor</a>
          </div>
        </li>
      </ul>

      <div class="navbar-nav ml-auto">
        <a type="button" class="btn btn-danger mx-2" href="{% url 'authentication:logout' %}">Log Out</a>
      </div>
    </div>
  </div>
</nav>

      
{% elif role == "atlet-non-kualifikasi" %}
  {% comment %} atlet non kualifikasi {% endcomment %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <a class="navbar-brand mt-2 mt-lg-0" href="#">
        <img src="https://comunidadbabadu.com/wp-content/uploads/2023/01/Babadu-Logo.png" height="30" alt="MDB Logo" loading="lazy" />
        <span class="badge rounded-pill badge-notification bg-success">Atlet Non Kualifikasi</span>
      </a>

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href=>Dashboard</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Ujian Kualifikasi
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% comment %} Atur href dibagian ini yah {% endcomment %}
                <a class="dropdown-item" href="{% url 'ujian_kualifikasi:show_ujian' %}">List Ujian Kualifikasi</a>
            <a class="dropdown-item" href="{% url 'ujian_kualifikasi:show_riwayat' %}">Riwayat Ujian Kualifikasi</a>
          </div>
        </li>

                
      </ul>

      <div class="navbar-nav ml-auto">
        <a type="button" class="btn btn-danger mx-2" href="{% url 'authentication:logout' %}">Log Out</a>
      </div>
    </div>
  </div>
</nav>

{% elif role == "umpire" %}
        <!-- Navbar untuk Umpire -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <a class="navbar-brand mt-2 mt-lg-0" href="#">
        <img src="https://comunidadbabadu.com/wp-content/uploads/2023/01/Babadu-Logo.png" height="30" alt="MDB Logo" loading="lazy" />
        <span class="badge rounded-pill badge-notification bg-success">Umpire</span>
      </a>

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authentication:home' %}">Dashboard</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Atlet
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% comment %} Atur href dibagian ini yah {% endcomment %}
            <a class="dropdown-item" href="{% url 'daftar_atlet:show_daftar_atlet' %}">Daftar Atlet</a>
          </div>
        </li>

               <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Ujian Kualifikasi
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% comment %} Atur href dibagian ini yah {% endcomment %}
            <a class="dropdown-item" href="{% url 'ujian_kualifikasi:create_ujian' %}">Buat Ujian Kualifikasi</a>
            <a class="dropdown-item" href="{% url 'ujian_kualifikasi:show_ujian' %}">List Ujian Kualifikasi</a>
            <a class="dropdown-item" href="{% url 'ujian_kualifikasi:show_riwayat' %}">Riwayat Ujian Kualifikasi</a>
          </div>
        </li>

               <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Event
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% comment %} Atur href dibagian ini yah {% endcomment %}
            <a class="dropdown-item" href="{% url 'pertandingan2:list_pertandingan' %}">List Partai Kompetisi</a>
          </div>
        </li>
      </ul>

      <div class="navbar-nav ml-auto">
        <a type="button" class="btn btn-danger mx-2" href="{% url 'authentication:logout' %}">Log Out</a>
      </div>
    </div>
  </div>
</nav>


{% elif role == "pelatih" %}
        <!-- Navbar untuk Pelatih -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <a class="navbar-brand mt-2 mt-lg-0" href="#">
        <img src="https://comunidadbabadu.com/wp-content/uploads/2023/01/Babadu-Logo.png" height="30" alt="MDB Logo" loading="lazy" />
        <span class="badge rounded-pill badge-notification bg-success">Pelatih</span>
      </a>

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authentication:home' %}">Dashboard</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Latih Atlet
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% comment %} Atur href dibagian ini yah {% endcomment %}
            <a class="dropdown-item" href="">Create Latih Atlet</a>
            <a class="dropdown-item" href="">List Atlet Dilatih</a>
          </div>
        </li>
      </ul>

      <div class="navbar-nav ml-auto">
        <a type="button" class="btn btn-danger mx-2" href="{% url 'authentication:logout' %}">Log Out</a>
      </div>
    </div>
  </div>
</nav>    
{% else %}
{% comment %} belum login {% endcomment %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <a class="navbar-brand mt-2 mt-lg-0" href="#">
          <img
            src="https://comunidadbabadu.com/wp-content/uploads/2023/01/Babadu-Logo.png"
            height="30"
            alt="MDB Logo"
            loading="lazy"
          />


        </a>
        
       
    </div>
  </nav>



{% endif %}

{% endblock content %}

templates/navbar.html
{% load static %}
{% block meta %}
{% endblock meta %}



{% block content %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <a class="navbar-brand mt-2 mt-lg-0" href="#">
          <img
            src="https://comunidadbabadu.com/wp-content/uploads/2023/01/Babadu-Logo.png"
            height="30"
            alt="MDB Logo"
            loading="lazy"
          />
        <span class="badge rounded-pill badge-notification bg-success">Atlet Non-Kualifikasi</span>

        </a>
        
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="#">Dashboard</a> 
            
            
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Ujian Kualifikasi
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{%url 'ujian_kualifikasi:show_ujian' %}">List Ujian Kualifikasi</a>
              <a class="dropdown-item" href="{%url 'ujian_kualifikasi:show_riwayat' %}">Riwayat Ujian Kualifikasi</a>
            </div>
          </li>
      <div class="d-flex align-items-center">
        <a type="button" class="btn btn-danger mx-2 " href="{% url 'authentication:logout' %}">Log Out</a>
      </div>
    </div>
  </nav>

{% endblock content %}